/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        void: '#0B0E17',
        ink: '#151928',
        violet: '#7B2FF7',
        blue: '#3B6BF7',
        electric: '#00D4FF',
        cyan: '#00E5FF',
        white: '#F8FAFF',
        silver: '#A0AEC0',
        // Kimi marketing palette (dark premium surfaces)
        'deep-navy': '#070B14',
        navy: '#0D1220',
        slate: '#151B2B',
        'muted-blue': '#5B6E8A',
        'soft-white': '#E2E8F0',
        'brand-blue': '#0072F5',
        'light-blue': '#4DA3FF',
        'electric-blue': '#00C6FF',
        'vivid-violet': '#7C3AED',
        'deep-violet': '#4C1D95',
        surface: '#F1F5F9',
        'surface-alt': '#E2E8F0',
        glass: 'rgba(255, 255, 255, 0.85)',
        'glass-border': 'rgba(123, 47, 247, 0.25)',
        'glass-border-hover': 'rgba(123, 47, 247, 0.45)',
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#EF4444',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        outfit: ['Outfit', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'hero': '4.5rem',
        'h1': '3.25rem',
        'h2': '2.5rem',
        'h3': '1.375rem',
        'h4': '1.125rem',
        'body-lg': '1.25rem',
        'body-sm': '0.875rem',
        'label': '0.8125rem',
        'nav': '0.9375rem',
        'stat': 'clamp(2.5rem, 5vw, 4rem)',
        'mono': '0.875rem',
      },
      lineHeight: {
        'hero': '0.95',
        'h1': '1.05',
        'h2': '1.1',
        'h3': '1.25',
        'h4': '1.3',
        'body-lg': '1.6',
        'body': '1.65',
        'body-sm': '1.55',
        'label': '1.4',
      },
      letterSpacing: {
        'hero': '0',
        'h1': '0',
        'h2': '0',
        'h3': '0',
        'label': '0.08em',
        'nav': '0.01em',
      },
      maxWidth: {
        'container': '1280px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'glass': '0 20px 60px rgba(123, 47, 247, 0.15)',
        'glow': '0 0 30px rgba(123, 47, 247, 0.4)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "meshBreathe": {
          "0%, 100%": { transform: "scale(1) translate(0, 0)" },
          "33%": { transform: "scale(1.05) translate(3%, -3%)" },
          "66%": { transform: "scale(0.95) translate(-2%, 2%)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(123,47,247,0.2)" },
          "50%": { boxShadow: "0 0 40px rgba(123,47,247,0.4)" },
        },
        "gradientMove": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "float-up": {
          "0%": { transform: "translateY(0) translateX(0)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateY(-100vh) translateX(20px)", opacity: "0" },
        },
        spin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "bounce-chevron": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "mesh-breathe": "meshBreathe 15s ease-in-out infinite",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
        "gradient-shift": "gradientMove 8s ease infinite",
        "float-up": "float-up 15s linear infinite",
        "spin-slow": "spin 4s linear infinite",
        "spin-slower": "spin 8s linear infinite",
        marquee: "marquee 30s linear infinite",
        "bounce-chevron": "bounce-chevron 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
